version: "3.8"
services:

  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 72NDP19t3SrX73
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: jr1B36!#CW151f
    networks:
      - app-network


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - app-network
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 72NDP19t3SrX73

volumes:
  db_data:

networks:
  app-network:
    driver: bridge